### ISSUE TITLE
Exifs in resized images

### ISSUE THREAD

**Issue by AntoineAA** [haytherecharlie/Imagenation#1]
Hi,
Is this plugin write the exif data (GPS, date, time...) in the resized images?
Thanks.

**Comment by haytherecharlie** [comment]
Hey Antoine, 

Sorry for the delayed response, writing custom exif data and erasing exif data is something I have on the roadmap for the package. However at the moment, the package is using existing exif data and using that to orient the image properly (i.e. ensure it's right-side-up).
